theme: minima
title: Iridis Alpha Theory
description: >
  It's not really a theory.

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  mwenge
    twitter: mwenge
    mastodon:
    - username: mwenge
      instance: mastodon.social
    
plugins:
  - jekyll-feed
  - jekyll-seo-tag

