theme: minima
title: Iridis Alpha Theory
description: >
  It's not really a theory.

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://twitter.com/mwenge" }
    
